apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensearch
  name: opensearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: analyzer
      port: 9600
      targetPort: 9600
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opensearch
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - env:
            - name: compatibility.override_main_response_version
              value: "true"
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
          image: opensearchproject/opensearch:1.3.20
          name: opensearch
          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            limits:
              cpu: 500m
              memory: "2Gi"
            requests:
              cpu: 500m
              memory: "2Gi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensearch-dashboards
  name: opensearch-dashboards
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: opensearch-dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opensearch-dashboards
  name: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
        - env:
            - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
              value: "true"
            - name: OPENSEARCH_HOSTS
              value: '["http://opensearch:9200"]'
          image: opensearchproject/opensearch-dashboards:1.3.20
          name: opensearch-dashboards
          ports:
            - containerPort: 5601
          resources:
            limits:
              cpu: 200m
              memory: "512Mi"
            requests:
              cpu: 100m
              memory: "256Mi"
      restartPolicy: Always
status: {}
